PATH =''
DB = {
	'mapName': PATH + '/data/mapName.json',
	'iconId': PATH + '/data/iconId.json',
	'mapData': PATH + '/data/MapData/{}.json',
	'mapImage': PATH + '/data/MapImage/{}.png',
	'iconImage': PATH + '/Icon/{}.png',
	'serverIcon': PATH + '/data/serverIcon.png',
	'dynamicData': 'https://war-service-live.foxholeservices.com/api/worldconquest/maps/{}/dynamic/public',
	'staticData': 'https://war-service-live.foxholeservices.com/api/worldconquest/maps/{}/static',
	'eventThread': 881662982160003113,
  'serverId': 881632566589915177,
	'mapReport': 'https://war-service-live.foxholeservices.com/api/worldconquest/warReport/{}',
	'warReport': 'https://war-service-live.foxholeservices.com/api/worldconquest/war',
	'Token': 'ODgxNjMyODI5NTQ3NjQyOTcy.GCb_U4.AcOcHxTXWm0jU2YVo4MziJ1PosDHj2LGxDUCmg',
	'startWar': 1664389802386,
  'iconFilter': [45,46,47, 56, 57, 58]
}

ICON_ID = {
  8: 'Forward Base 1',
  11: 'Hospital',
  12: 'Vehicle Factory',
  13: 'Armory',
  14: 'Supply Station',
  15: 'Workshop',
  16: 'Manufacturing Plant',
  17: 'Refinery',
  18: 'Shipyard',
  19: 'Tech Center',
  20: 'Salvage Field',
  21: 'Component Field',
  22: 'Fuel Field',
  23: 'Sulfur Field',
  24: 'World Map Tent',
  25: 'Travel Tent',
  26: 'Training Area',
  27: 'Keep',
  28: 'Observation Tower',
  29: 'Fort',
  30: 'Troop Ship',
  32: 'Sulfur Mine',
  33: 'Storage Facility',
  34: 'Factory',
  35: 'Safehouse',
  36: 'Ammo Factory',
  37: 'Rocket Site',
  38: 'Salvage Mine',
  39: 'Construction Yard',
  40: 'Component Mine',
  45: 'Relic Base 1',
  46: 'Relic Base 2',
  47: 'Relic Base 3',
  51: 'Mass Production Factory',
  52: 'Seaport',
  53: 'Coastal Gun',
  54: 'SoulFactory',
  56: 'Town Base 1',
  57: 'Town Base 2',
  58: 'Town Base 3',
  59: 'Storm Cannon',
  60: 'Intel Center',
  61: 'Coal Field',
  62: 'Oil Field'
}

MAP_NAME = [
  "TheFingers",
  "GreatMarch",
  "TempestIsland",
  "MarbanHollow",
  "ViperPit",
  "BasinSionnach",
  "DeadLands",
  "Heartlands",
  "EndlessShore",
  "Westgate",
  "Oarbreaker",
  "Acrithia",
  "MooringCounty",
  "WeatheredExpanse",
  "LochMor",
  "MorgensCrossing",
  "Stonecradle",
  "AllodsBight",
  "Kalokai",
  "RedRiver",
  "Origin",
  "HowlCounty",
  "ShackledChasm",
  "SpeakingWoods",
  "Terminus",
  "LinnMercy",
  "ClansheadValley",
  "Godcrofts",
  "NevishLine",
  "CallumsCape",
  "FishermansRow",
  "UmbralWildwood",
  "ReachingTrail",
  "CallahansPassage",
  "AshFields",
  "DrownedVale",
  "FarranacCoast"
]
