PATH = './app'
DB = {
	'mapName': PATH + '/data/mapName.json',
	'iconId': PATH + '/data/iconId.json',
	'mapData': PATH + '/data/MapData/{}.json',
	'mapImage': PATH + '/data/MapImage/{}.png',
	'iconImage': PATH + '/Icon/{}.png',
	'serverIcon': PATH + '/data/serverIcon.png',
	'dynamicData': 'https://war-service-live.foxholeservices.com/api/worldconquest/maps/{}/dynamic/public',
	'staticData': 'https://war-service-live.foxholeservices.com/api/worldconquest/maps/{}/static',
	'eventThread': 881662982160003113,
  'serverId': 881632566589915177,
	'mapReport': 'https://war-service-live.foxholeservices.com/api/worldconquest/warReport/{}',
	'warReport': 'https://war-service-live.foxholeservices.com/api/worldconquest/war',
	'Token': 'ODgxNjMyODI5NTQ3NjQyOTcy.GCb_U4.AcOcHxTXWm0jU2YVo4MziJ1PosDHj2LGxDUCmg',
	'startWar': 1664389802386,
  'iconFilter': [45,46,47, 56, 57, 58]
}

ICON_ID = {
  8: 'ForwardBase1',
  11: 'Hospital',
  12: 'VehicleFactory',
  13: 'Armory',
  14: 'SupplyStation',
  15: 'Workshop',
  16: 'ManufacturingPlant',
  17: 'Refinery',
  18: 'Shipyard',
  19: 'TechCenter',
  20: 'SalvageField',
  21: 'ComponentField',
  22: 'FuelField',
  23: 'SulfurField',
  24: 'WorldMapTent',
  25: 'TravelTent',
  26: 'TrainingArea',
  27: 'Keep',
  28: 'ObservationTower',
  29: 'Fort',
  30: 'TroopShip',
  32: 'SulfurMine',
  33: 'StorageFacility',
  34: 'Factory',
  35: 'Safehouse',
  36: 'AmmoFactory',
  37: 'RocketSite',
  38: 'SalvageMine',
  39: 'ConstructionYard',
  40: 'ComponentMine',
  45: 'RelicBase1',
  46: 'RelicBase2',
  47: 'RelicBase3',
  51: 'MassProductionFactory',
  52: 'Seaport',
  53: 'CoastalGun',
  54: 'SoulFactory',
  56: 'TownBase1',
  57: 'TownBase2',
  58: 'TownBase3',
  59: 'StormCannon',
  60: 'IntelCenter',
  61: 'CoalField',
  62: 'OilField'
}

MAP_NAME = [
  "TheFingers",
  "GreatMarch",
  "TempestIsland",
  "MarbanHollow",
  "ViperPit",
  "BasinSionnach",
  "DeadLands",
  "Heartlands",
  "EndlessShore",
  "Westgate",
  "Oarbreaker",
  "Acrithia",
  "MooringCounty",
  "WeatheredExpanse",
  "LochMor",
  "MorgensCrossing",
  "Stonecradle",
  "AllodsBight",
  "Kalokai",
  "RedRiver",
  "Origin",
  "HowlCounty",
  "ShackledChasm",
  "SpeakingWoods",
  "Terminus",
  "LinnMercy",
  "ClansheadValley",
  "Godcrofts",
  "NevishLine",
  "CallumsCape",
  "FishermansRow",
  "UmbralWildwood",
  "ReachingTrail",
  "CallahansPassage",
  "AshFields",
  "DrownedVale",
  "FarranacCoast"
]
